# https://github.com/tmu-muellerj/docker-nagios/blob/master/Dockerfile
FROM manios/nagios:latest

RUN apk add --no-cache apache2-ldap

# Add edge repositories for consistent dependency resolution
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main"      >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing"   >> /etc/apk/repositories


# Install required packages from edge
RUN apk update && \
    apk add --no-cache hiredis apache-mod-auth-openidc
