services:
  nagios_etc: &backup_service
    image: offen/docker-volume-backup:v2
    environment: &backup_environment
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
    volumes:
      - nagios_etc:/backup:ro
      - /var/lib/docker/backups/nagios_etc:/archive

  nagios_var:
    <<: *backup_service
    environment:
      <<: *backup_environment
    volumes:
      - nagios_var:/backup:ro
      - /var/lib/docker/backups/nagios_var:/archive

volumes:
  nagios_etc:
  nagios_var:
