version: '3.8'
services:
  nagios:
    volumes: !override
      - nagios_etc:/opt/nagios/etc
      - nagios_var:/opt/nagios/var
    environment:
      NAGIOSADMIN_USER: "nagiosadmin"

volumes:
  nagios_etc:
  nagios_var:
