version: '3.8'
services:
  nagios:
    build:
      context: .
      dockerfile: Dockerfile_TMU
      platforms:
        - linux/amd64
      tags:
        - tmumuellerj/docker-nagios:tmu
    image: tmumuellerj/docker-nagios:tmu
    volumes: !override
      - nagios_etc:/opt/nagios/etc
      - nagios_var:/opt/nagios/var
      - nagios_ssh:/home/nagios/.ssh
      - nagios_confd:/etc/apache2/conf.d
      - myCertificates:/etc/apache2/ssl
    environment:
      NAGIOSADMIN_USER: "nagiosadmin"

volumes:
  nagios_etc:
  nagios_var:
  nagios_ssh:
  nagios_confd:
  myCertificates:
    external: true
